# Generated by Django 5.2.1 on 2025-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('name', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام')),
                ('lastname', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام خانوادگی')),
                ('fullname', models.CharField(blank=True, max_length=55, null=True, verbose_name='نام ونام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='آدرس ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین؟')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب های کاربری',
            },
        ),
    ]
